// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsJ9A2Mlcwr-Oi0xs-ASNcoNBxoCUQeY',
    appId: '1:160360809616:web:147d4b6ac1a9768a570415',
    messagingSenderId: '160360809616',
    projectId: 'newsapp-e8764',
    authDomain: 'newsapp-e8764.firebaseapp.com',
    storageBucket: 'newsapp-e8764.appspot.com',
    measurementId: 'G-BC9NY9THGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJOHxrQLO1aUJhFTW13KnJDpAw0wgx_c',
    appId: '1:160360809616:android:308b5a96f0ffb890570415',
    messagingSenderId: '160360809616',
    projectId: 'newsapp-e8764',
    storageBucket: 'newsapp-e8764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBteIijKYp_bIFc0sPpLaG-9lrwY4kuBhU',
    appId: '1:160360809616:ios:d0a220d8d37ea2d2570415',
    messagingSenderId: '160360809616',
    projectId: 'newsapp-e8764',
    storageBucket: 'newsapp-e8764.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBteIijKYp_bIFc0sPpLaG-9lrwY4kuBhU',
    appId: '1:160360809616:ios:d0a220d8d37ea2d2570415',
    messagingSenderId: '160360809616',
    projectId: 'newsapp-e8764',
    storageBucket: 'newsapp-e8764.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvsJ9A2Mlcwr-Oi0xs-ASNcoNBxoCUQeY',
    appId: '1:160360809616:web:1099efe56d9e98b2570415',
    messagingSenderId: '160360809616',
    projectId: 'newsapp-e8764',
    authDomain: 'newsapp-e8764.firebaseapp.com',
    storageBucket: 'newsapp-e8764.appspot.com',
    measurementId: 'G-2LRVN8VPFN',
  );
}
